services:
  # nginx:
  #   image: nginx:1.27.5@sha256:c15da6c91de8d2f436196f3a768483ad32c258ed4e1beb3d367a27ed67253e66
  #   ports:
  #     - 80:80
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  pihole:
    image: pihole/pihole:2026.04.0@sha256:300cc8f9e966b00440358aafef21f91b32dfe8887e8bd9a6193ed1c4328655d4
    environment:
      TZ: 'Europe/Stockholm'
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      - 80:80
    restart: unless-stopped
    volumes:
      - './pihole.toml:/etc/pihole/pihole.toml'
