---
version: 2

updates:
  - package-ecosystem: "terraform"
    directories:
      - "/terraform/cloudflare"
      - "/terraform/edgerouter"
      - "/terraform/pihole"
      - "/terraform/unifi"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/dockerfiles/ansible"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/dockerfiles/ansible"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker-compose"
    directory: "/docker-compose/pihole"
    schedule:
      interval: "monthly"
