---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/cloudflare"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "/terraform/edgerouter"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "/terraform/pihole"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "/terraform/unifi"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/dockerfiles/ansible"
    schedule:
      interval: "monthly"
