version: 2

updates:

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
