---
version: 2

updates:
  - package-ecosystem: "terraform"
    directories:
      - "/apps/cloudflare"
      - "/apps/elk"
      - "/apps/grafana"
      - "/apps/modules/**/*.tf"
      - "/apps/ovh"
      - "/apps/pihole"
      - "/apps/truenas"
      - "/apps/unifi"

    schedule:
      interval: "monthly"

  - package-ecosystem: "docker-compose"
    directories:
      - "/devices/margarita/pihole"

      - "/devices/jameson/elk"
      - "/devices/jameson/prometheus"

      - "/devices/baileys/prometheus"

      - "/doco-cd/jameson"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
