services:
  caddy:
    image: badouralix/caddy-dns-ovh:2.9.1@sha256:dd12a91dd2af70e3855cf1806ef7750526d740e6290f43a43e82ff90a8e881a4
    restart: unless-stopped
    pull_policy: never
    environment:
      - OVH_ENDPOINT
      - APPLICATION_KEY
      - APPLICATION_SECRET
      - CONSUMER_KEY
    ports:
      - "443:443"
      - "443:443/udp"
    networks:
      - proxy
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    name: proxy
