services:
  caddy:
    image: badouralix/caddy-dns-ovh:2.9.1@sha256:c603d5cf33d38c1235d839ae9b559c2dc9068c67abc7b20ced01a30bf3b624c9
    restart: unless-stopped
    pull_policy: never
    environment:
      - OVH_ENDPOINT
      - APPLICATION_KEY
      - APPLICATION_SECRET
      - CONSUMER_KEY
    ports:
      - "443:443"
      - "443:443/udp"
    networks:
      - proxy
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    name: proxy
