---
name: jameson-prometheus
repository_url: https://github.com/jlilja/infra.git
working_dir: devices/jameson/prometheus/
---
name: jameson-elk
repository_url: https://github.com/jlilja/infra.git
working_dir: devices/jameson/elk/
