version: '3'

includes:
  terraform: terraform/Taskfile.yml

tasks:

  format:
    desc: Run Terraform format check
    dir: terraform
    cmds:
      - task: terraform:format

  init:
    desc: Run Terraform init
    cmds:
      - task: terraform:init

  plan:
    desc: Run Terraform plan
    dir: terraform
    cmds:
      - task: terraform:plan
