---
version: "3"

includes:
  terraform:cloudflare: terraform/cloudflare/Taskfile.yml
  terraform:edgerouter: terraform/edgerouter/Taskfile.yml
  terraform:pihole: terraform/pihole/Taskfile.yml

  k8s:webserver: k8s/apps/webserver/Taskfile.yml

  ansible:pihole: ansible/pihole/Taskfile.yml
  ansible:kubernetes: ansible/kubernetes/Taskfile.yml
  ansible:edgerouter: ansible/edgerouter/Taskfile.yml

tasks:
  terraform-format:
    cmds:
      - task terraform:cloudflare:format
      - task terraform:edgerouter:format
      - task terraform:pihole:format
