---
version: "3"

includes:
  terraform:cloudflare: terraform/cloudflare/Taskfile.yml
  terraform:edgerouter: terraform/edgerouter/Taskfile.yml
  terraform:pihole: terraform/pihole/Taskfile.yml

  k8s:webserver: k8s/apps/webserver/Taskfile.yml

  docker: dockerfiles/Taskfile.yml

  ansible:
    taskfile: ansible/Taskfile.yml
    dir: ansible

tasks:
  terraform-format:
    cmds:
      - task terraform:cloudflare:format
      - task terraform:edgerouter:format
      - task terraform:pihole:format
