---
version: "3"

includes:
  terraform:cloudflare: apps/cloudflare/Taskfile.yml
  terraform:elk: apps/elk/Taskfile.yml
  terraform:unifi: apps/unifi/Taskfile.yml
  terraform:grafana: apps/grafana/Taskfile.yml

tasks:
  terraform-format:
    cmds:
      - task terraform:cloudflare:format
