---
- name: Create network groups
  community.network.edgeos_config:
    lines:
      - set firewall group network-group RFC1918 description 'RFC1918 ranges'
      - set firewall group network-group RFC1918 network 192.168.0.0/16
      - set firewall group network-group RFC1918 network 172.16.0.0/12
      - set firewall group network-group RFC1918 network 10.0.0.0/8

      - set firewall group address-group Synology-URLs description 'list of all known addresses used for Synology NAS services'
      - set firewall group address-group Synology-URLs address 3.98.65.151
      - set firewall group address-group Synology-URLs address 159.100.4.215
      - set firewall group address-group Synology-URLs address 52.29.61.103
      - set firewall group address-group Synology-URLs address 3.164.230.105
      - set firewall group address-group Synology-URLs address 108.157.229.35
      - set firewall group address-group Synology-URLs address 132.226.8.169
      - set firewall group address-group Synology-URLs address 84.200.39.196
      - set firewall group address-group Synology-URLs address 167.99.175.230
      - set firewall group address-group Synology-URLs address 64.227.48.237
      - set firewall group address-group Synology-URLs address 112.121.122.67
      - set firewall group address-group Synology-URLs address 52.85.49.2
      - set firewall group address-group Synology-URLs address 3.164.68.100
      - set firewall group address-group Synology-URLs address 143.244.58.91
      - set firewall group address-group Synology-URLs address 185.152.64.138
      - set firewall group address-group Synology-URLs address 89.187.188.251
      - set firewall group address-group Synology-URLs address 3.164.68.20
      - set firewall group address-group Synology-URLs address 108.156.22.87
      - set firewall group address-group Synology-URLs address 108.157.214.7
      - set firewall group address-group Synology-URLs address 34.214.97.194
      - set firewall group address-group Synology-URLs address 52.29.61.103
      - set firewall group address-group Synology-URLs address 108.157.214.115
      - set firewall group address-group Synology-URLs address 89.187.169.109
      - set firewall group address-group Synology-URLs address 185.102.219.107
      - set firewall group address-group Synology-URLs address 138.199.37.169
      - set firewall group address-group Synology-URLs address 203.74.127.91
      - set firewall group address-group Synology-URLs address 3.123.206.192
      - set firewall group address-group Synology-URLs address 18.195.145.6
      - set firewall group address-group Synology-URLs address 46.101.121.10
      - set firewall group address-group Synology-URLs address 46.101.119.59
      - set firewall group address-group Synology-URLs address 142.93.235.134
      - set firewall group address-group Synology-URLs address 142.93.235.17
      - set firewall group address-group Synology-URLs address 185.93.2.158
      - set firewall group address-group Synology-URLs address 185.93.2.155
      - set firewall group address-group Synology-URLs address 185.93.2.157
      - set firewall group address-group Synology-URLs address 185.93.2.187
      - set firewall group address-group Synology-URLs address 3.164.230.76
      - set firewall group address-group Synology-URLs address 52.29.61.103
      - set firewall group address-group Synology-URLs address 104.22.0.171
      - set firewall group address-group Synology-URLs address 108.157.214.25
      - set firewall group address-group Synology-URLs address 3.164.240.106
      - set firewall group address-group Synology-URLs address 108.157.214.102
      - set firewall group address-group Synology-URLs address 123.51.153.87
      - set firewall group address-group Synology-URLs address 138.197.222.19
      - set firewall group address-group Synology-URLs address 52.10.12.61
      - set firewall group address-group Synology-URLs address 52.39.32.173
      - set firewall group address-group Synology-URLs address 142.93.83.92
      - set firewall group address-group Synology-URLs address 142.93.91.101
      - set firewall group address-group Synology-URLs address 3.164.240.59
      - set firewall group address-group Synology-URLs address 52.85.49.75
      - set firewall group address-group Synology-URLs address 172.67.75.147
      - set firewall group address-group Synology-URLs address 108.157.214.115
      - set firewall group address-group Synology-URLs address 52.85.49.96
      - set firewall group address-group Synology-URLs address 108.157.214.112
      - set firewall group address-group Synology-URLs address 209.58.169.46
      - set firewall group address-group Synology-URLs address 209.58.169.44
      - set firewall group address-group Synology-URLs address 46.101.121.10
      - set firewall group address-group Synology-URLs address 142.93.83.92
      - set firewall group address-group Synology-URLs address 108.157.214.71
      - set firewall group address-group Synology-URLs address 46.101.119.59
      - set firewall group address-group Synology-URLs address 142.93.91.101
      - set firewall group address-group Synology-URLs address 108.157.214.71
      - set firewall group address-group Synology-URLs address 142.93.235.134
      - set firewall group address-group Synology-URLs address 142.93.235.17
      - set firewall group address-group Synology-URLs address 206.189.219.255
      - set firewall group address-group Synology-URLs address 159.100.4.222
      - set firewall group address-group Synology-URLs address 35.183.151.54
      - set firewall group address-group Synology-URLs address 159.100.4.208
      - set firewall group address-group Synology-URLs address 108.157.229.117
      - set firewall group address-group Synology-URLs address 123.51.153.87
      - set firewall group address-group Synology-URLs address 125.228.116.235
      - set firewall group address-group Synology-URLs address 114.32.252.100
      - set firewall group address-group Synology-URLs address 122.116.168.124
      - set firewall group address-group Synology-URLs address 114.32.67.238
      - set firewall group address-group Synology-URLs address 114.32.67.211
      - set firewall group address-group Synology-URLs address 114.32.67.34
      - set firewall group address-group Synology-URLs address 108.157.214.55
      - set firewall group address-group Synology-URLs address 108.157.214.25
      - set firewall group address-group Synology-URLs address 3.164.243.76
      - set firewall group address-group Synology-URLs address 3.174.113.2
      - set firewall group address-group Synology-URLs address 52.39.206.233
      - set firewall group address-group Synology-URLs address 64.124.13.135
      - set firewall group address-group Synology-URLs address 185.59.223.109
      - set firewall group address-group Synology-URLs address 89.187.177.150
      - set firewall group address-group Synology-URLs address 89.187.185.196
      - set firewall group address-group Synology-URLs address 89.187.185.91
      - set firewall group address-group Synology-URLs address 89.187.185.92
      - set firewall group address-group Synology-URLs address 3.164.206.121
