---

# Linting of this file is disabled until the following issue is resolved:
# https://github.com/ansible/ansible-lint/issues/3607

- name: Set
  hosts: edgerouter1
  connection: network_cli

  tasks:

    - name: Configure system settings
      community.network.edgeos_config:
        lines:
          # Set hostname settings
          - set system host-name edgerouter

          # Disable ubnt services
          - set service ubnt-discover disable
          - set service unms disable

          # Set NTP servers
          - set system ntp server 0.ubnt.pool.ntp.org
          - set system ntp server 1.ubnt.pool.ntp.org
          - set system ntp server 2.ubnt.pool.ntp.org
          - set system ntp server 3.ubnt.pool.ntp.org

          # Set all of the remote servers
          - set system name-server 8.8.8.8
          - set system name-server 4.2.2.1

          - set system time-zone UTC

          # Enable deep packet analysis
          # https://help.ui.com/hc/en-us/articles/204951104-EdgeRouter-Deep-Packet-Inspection-Engine
          - set system traffic-analysis dpi enable
          - set system traffic-analysis export enable

          # Don't tell Ubiquiti about your issues.
          - set system analytics-handler send-analytics-report false
          - set system crash-handler send-crash-report false

          # Hairpinning is when services wants to go out to the NAT and get back into the network.
          # AFAIK this is not needed for me at the moment.
          # Will be commented out until VLANS are defined
          # - set port-forward hairpin-nat disable

          # Setup WAN entrypoint for eth0.
          # Setup interface to use DHCP and duplex speed to be auto negotiated
          - set interfaces ethernet eth0 description internet
          - set interfaces ethernet eth0 address dhcp
          - set interfaces ethernet eth0 duplex auto

          # Setup LAN interface for home network.
          # 192.168.1.1/24, nothing special.
          - set interfaces ethernet eth1 description lan
          - set interfaces ethernet eth1 address 192.168.1.1/24
          - set interfaces ethernet eth1 duplex auto

          # Not used. Eth1 pushes traffic to a switch so no need to the remainin interface(s).
          - set interfaces ethernet eth2 description -
          - set interfaces ethernet eth2 disable

    - name: Setup trusted network
      community.network.edgeos_config:
        lines:

          # vlan setup
          - set interfaces ethernet eth1 vif 10 description 'VLAN 10 - Trusted'
          - set interfaces ethernet eth1 vif 10 address 192.168.10.1/24

          # dhcp setup
          - set service dhcp-server shared-network-name trusted authoritative enable
          - set service dhcp-server shared-network-name trusted subnet 192.168.10.0/24 default-router 192.168.10.1 # Router
          - set service dhcp-server shared-network-name trusted subnet 192.168.10.0/24 dns-server 192.168.10.1 # DNS 1
          - set service dhcp-server shared-network-name trusted subnet 192.168.10.0/24 lease 3600 # Lease time

          - set service dhcp-server shared-network-name trusted subnet 192.168.10.0/24 start 192.168.10.10 stop 192.168.10.254

          # dns server for vlan
          - set service dns forwarding listen-on eth1.10

    - name: Setup homelab network
      community.network.edgeos_config:
        lines:

          # vlan setup
          - set interfaces ethernet eth1 vif 20 description 'VLAN 20 - Homelab'
          - set interfaces ethernet eth1 vif 20 address 192.168.20.1/24

          # dhcp setup
          - set service dhcp-server shared-network-name homelab authoritative enable
          - set service dhcp-server shared-network-name homelab subnet 192.168.20.0/24 default-router 192.168.20.1 # Router
          - set service dhcp-server shared-network-name homelab subnet 192.168.20.0/24 dns-server 192.168.20.1 # DNS 1
          - set service dhcp-server shared-network-name homelab subnet 192.168.20.0/24 lease 3600 # Lease time

          - set service dhcp-server shared-network-name homelab subnet 192.168.20.0/24 start 192.168.20.10 stop 192.168.20.254

          # dns server for vlan
          - set service dns forwarding listen-on eth1.20

    - name: Setup DNS network
      community.network.edgeos_config:
        lines:

          # vlan setup
          - set interfaces ethernet eth1 vif 30 description 'VLAN 30 - DNS'
          - set interfaces ethernet eth1 vif 30 address 192.168.30.1/24

          # dhcp setup
          - set service dhcp-server shared-network-name dns authoritative enable
          - set service dhcp-server shared-network-name dns subnet 192.168.30.0/24 default-router 192.168.30.1 # Router
          - set service dhcp-server shared-network-name dns subnet 192.168.30.0/24 dns-server 192.168.30.1 # DNS 1
          - set service dhcp-server shared-network-name dns subnet 192.168.30.0/24 lease 3600 # Lease time

          - set service dhcp-server shared-network-name dns subnet 192.168.30.0/24 start 192.168.30.10 stop 192.168.30.254

          # dns server for vlan
          - set service dns forwarding listen-on eth1.30

    - name: Setup infrastructure network
      community.network.edgeos_config:
        lines:

          # vlan setup
          - set interfaces ethernet eth1 vif 40 description 'VLAN 40 - Infrastructure'
          - set interfaces ethernet eth1 vif 40 address 192.168.40.1/24

          # dhcp setup
          - set service dhcp-server shared-network-name infra authoritative enable
          - set service dhcp-server shared-network-name infra subnet 192.168.40.0/24 default-router 192.168.40.1 # Router
          - set service dhcp-server shared-network-name infra subnet 192.168.40.0/24 dns-server 192.168.40.1 # DNS 1
          - set service dhcp-server shared-network-name infra subnet 192.168.40.0/24 lease 3600 # Lease time

          - set service dhcp-server shared-network-name infra subnet 192.168.40.0/24 start 192.168.40.10 stop 192.168.40.254

          # dns server for vlan
          - set service dns forwarding listen-on eth1.40

    - name: Setup NAS network
      community.network.edgeos_config:
        lines:

          # vlan setup
          - set interfaces ethernet eth1 vif 50 description 'VLAN 50 - NAS'
          - set interfaces ethernet eth1 vif 50 address 192.168.50.1/24

          # dhcp setup
          - set service dhcp-server shared-network-name nas authoritative enable
          - set service dhcp-server shared-network-name nas subnet 192.168.50.0/24 default-router 192.168.50.1 # Router
          - set service dhcp-server shared-network-name nas subnet 192.168.50.0/24 dns-server 192.168.50.1 # DNS 1
          - set service dhcp-server shared-network-name nas subnet 192.168.50.0/24 lease 3600 # Lease time

          - set service dhcp-server shared-network-name nas subnet 192.168.50.0/24 start 192.168.50.10 stop 192.168.50.254

          # dns server for vlan
          - set service dns forwarding listen-on eth1.50

    - name: Setup IoT network
      community.network.edgeos_config:
        lines:

          # vlan setup
          - set interfaces ethernet eth1 vif 60 description 'VLAN 60 - IoT'
          - set interfaces ethernet eth1 vif 60 address 192.168.60.1/24

          # dhcp setup
          - set service dhcp-server shared-network-name iot authoritative enable
          - set service dhcp-server shared-network-name iot subnet 192.168.60.0/24 default-router 192.168.60.1 # Router
          - set service dhcp-server shared-network-name iot subnet 192.168.60.0/24 dns-server 192.168.60.1 # DNS 1
          - set service dhcp-server shared-network-name iot subnet 192.168.60.0/24 lease 3600 # Lease time

          - set service dhcp-server shared-network-name iot subnet 192.168.60.0/24 start 192.168.60.10 stop 192.168.60.254

          # dns server for vlan
          - set service dns forwarding listen-on eth1.60
