---
- name: Create firewall ruleset for hue smart lightning
  community.network.edgeos_config:
    lines:
      - set firewall name {{ edgerouter_firewall_hue_fw_name }} default-action drop
      - set firewall name {{ edgerouter_firewall_hue_fw_name }} description 'Trafic IN'

      - set firewall name {{ edgerouter_firewall_hue_fw_name }} rule 10 action accept
      - set firewall name {{ edgerouter_firewall_hue_fw_name }} rule 10 description 'Allow trafic from RFC 1918'
      - set firewall name {{ edgerouter_firewall_hue_fw_name }} rule 10 destination group network-group RFC1918

      - set interfaces ethernet eth1 vif 60 firewall in name {{ edgerouter_firewall_hue_fw_name }}
