---
version: "3"

tasks:
  format:
    desc: Format all Terraform files
    dir: terraform/unifi
    cmds:
      - terraform fmt -check -diff -recursive

  validate:
    desc: Validate all Terraform files
    dir: terraform/unifi
    cmds:
      - terraform validate

  init:
    desc: Initializes the Terraform project
    dir: terraform/unifi
    cmds:
      - terraform init

  plan:
    desc: Plan new Terraform changes
    dir: terraform/unifi
    cmds:
      - terraform plan

  apply:
    desc: Apply new Terraform changes
    dir: terraform/unifi
    cmds:
      - terraform apply
