---

- name: Ansible Copy File
  ansible.builtin.copy:
    src: "/pihole"
    dest: /home/pi
    owner: pi
    group: pi
    mode: '0644'

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: pihole
