---
version: "3"

includes:
  elk:
    taskfile: elk/Taskfile.yml
    dir: elk

env:
  LENNARTS: ansible@lennarts.local
  MARGARITA: pi@margarita.local

tasks:
  copy-elk:
    desc: "Copy elk docker-compose project"
    cmds:
      - scp -r docker-compose/elk $LENNARTS:/home/ansible

  copy-pihole:
    desc: "Copy pihole docker-compose project"
    cmds:
      - scp -r docker-compose/pihole $MARGARITA:/home/pi

  copy-all-docker-compose-projects:
    desc: "Copy all docker-compose projects"
    cmds:
      - task: copy-elk
      - task: copy-pihole
