---
- name: Configure system settings
  community.network.edgeos_config:
    lines:
      # Set hostname settings
      - set system host-name edgerouter

      - set system time-zone UTC

      # Enable deep packet analysis
      # https://help.ui.com/hc/en-us/articles/204951104-EdgeRouter-Deep-Packet-Inspection-Engine
      - set system traffic-analysis dpi enable
      - set system traffic-analysis export enable

      # Hairpinning is when services wants to go out to the NAT and get back into the network.
      # AFAIK this is not needed for me at the moment.
      # Will be commented out until VLANS are defined
      # - set port-forward hairpin-nat disable

      # Setup WAN entrypoint for eth0.
      # Setup interface to use DHCP and duplex speed to be auto negotiated
      - set interfaces ethernet eth0 description internet
      - set interfaces ethernet eth0 address dhcp
      - set interfaces ethernet eth0 duplex auto

      # Setup LAN interface for home network.
      # 192.168.1.1/24, nothing special.
      - set interfaces ethernet eth1 description lan
      - set interfaces ethernet eth1 address 192.168.1.1/24
      - set interfaces ethernet eth1 duplex auto

      # Not used. Eth1 pushes traffic to a switch so no need to the remainin interface(s).
      - set interfaces ethernet eth2 description -
      - set interfaces ethernet eth2 disable

- name: Disable crash reports
  community.network.edgeos_config:
    lines:
      - set system analytics-handler send-analytics-report false
      - set system crash-handler send-crash-report false

- name: Disable ubnt online services
  community.network.edgeos_config:
    lines:
      - set service ubnt-discover disable
      - set service unms disable

- name: Set NTP servers
  community.network.edgeos_config:
    lines:
      - "set system ntp server {{ item }}"
  loop:
    - 0.ubnt.pool.ntp.org
    - 1.ubnt.pool.ntp.org
    - 2.ubnt.pool.ntp.org
    - 3.ubnt.pool.ntp.org


- name: Set DNS servers
  community.network.edgeos_config:
    lines:
      - set system name-server 8.8.8.8
      - set system name-server 4.2.2.1
