---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
- name: Git clone pihole repository
  ansible.builtin.git:
    repo: "{{ pihole_repository }}"
    dest: "/home/{{ ansible_user }}/pihole"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Ensures /etc/pihole dir exists
  ansible.builtin.file:
    path: "/etc/pihole"
    state: directory

# A file transfer will make Ansible always report a change.
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy setupVars
  ansible.builtin.copy:
    src: ./setupVars.conf
    dest: /etc/pihole/setupVars.conf

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
- name: Install pihole unattended
  ansible.builtin.shell: bash /home/jserver/pihole/automated\ install/basic-install.sh --unattended
