---

- name: Git clone pihole repository
  ansible.builtin.git:
    repo: 'https://github.com/pi-hole/pi-hole.git'
    dest: /home/jserver/pihole

- name: Ensures /etc/pihole dir exists
  ansible.builtin.file:
    path: "/etc/pihole"
    state: directory

# A file transfer will make Ansible always report a change.
- name: Copy setupVars
  ansible.builtin.copy:
    src: ./setupVars.conf
    dest: /etc/pihole/setupVars.conf

- name: Install pihole unattended
  ansible.builtin.shell: bash /home/jserver/pihole/automated\ install/basic-install.sh --unattended
