---
nodes:
  hosts:
    kmain:
      ansible_host: 192.168.1.105
      ansible_user: kmain
    kworker:
      ansible_host: 192.168.1.104
      ansible_user: kworker1

  vars:
    etc_hosts:
      - ip: 192.168.1.105
        host: "kmain.local"
      - ip: 192.168.1.104
        host: "kworker1.local"
