---
version: "3"

tasks:
  ping-host:
    desc: "Ping the kubernetes node(s) using ansible module ping"
    dir: "ansible/kubernetes"
    cmds:
      - ansible all -i ./inventory.yml -m ping

  install-dependencies:
    desc: "Install docker and kubernetes"
    dir: "ansible/kubernetes"
    cmds:
      - ansible-playbook -i ./inventory.yml ./install_deps.yml --ask-become-pass

  update-dependencies:
    desc: "Update dnf packages"
    dir: "ansible/kubernetes"
    cmds:
      - ansible-playbook -i ./inventory.yml ./update_deps.yml --ask-become-pass

  harden-ssh:
    desc: "Secure ssh configs"
    dir: "ansible/kubernetes"
    cmds:
      - ansible-playbook -i ./inventory.yml ./harden_ssh.yml --ask-become-pass
