---

- name: Install dependencies
  hosts: kube1
  become: true
  tasks:

    - name: Install docker plugins core
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Add docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install docker engine, containerd, and docker compose
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Add docker group
      ansible.builtin.group:
        name: "{{ docker_group }}"
        state: present

    - name: Add ansible user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: "{{ docker_group }}"

    - name: Install the nginx rpm from a remote repo
      ansible.builtin.dnf:
        name: 'https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm'
        state: present
        disable_gpg_check: true
