---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Ensures /etc/pihole dir exists
  ansible.builtin.file:
    path: "/etc/pihole"
    state: directory

# A file transfer will make Ansible always report a change.
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy setupVars
  ansible.builtin.template:
    src: templates/setupVars.j2
    dest: /etc/pihole/setupVars.conf
