---

# Linting of this file is disabled until the following issue is resolved:
# https://github.com/ansible/ansible-lint/issues/3607

- name: Set
  hosts: edgerouters
  connection: network_cli

  tasks:
    - name: System configuration
      ansible.builtin.import_role:
        name: edgerouter_system_configure

    - name: Standard firewall defaults
      ansible.builtin.import_role:
        name: edgerouter_firewall_standard_rules

    - name: Setup trusted network
      ansible.builtin.import_role:
        name: edgerouter_vlan_setup

    - name: Create RFC1918 group
      ansible.builtin.import_role:
        name: edgerouter_create_network_groups

    - name: Setup iot firewall
      ansible.builtin.import_role:
        name: edgerouter_firewall_hue
      vars:
        fw_name: HUE_IN
