---

- name: Configure edgerouter firewall
  hosts: all
  connection: network_cli

  tasks:
    - name: Standard firewall defaults
      ansible.builtin.import_role:
        name: edgerouter_firewall_wan

    - name: Setup ds418p firewall
      ansible.builtin.import_role:
        name: edgerouter_firewall_ds418p

    - name: Setup iot firewall
      ansible.builtin.import_role:
        name: edgerouter_firewall_iot

    - name: Setup dns firewall
      ansible.builtin.import_role:
        name: edgerouter_firewall_dns
