---

- name: Set synoinfo settings
  hosts: ds418
  become: true

  vars_prompt:

    - name: synology_username
      prompt: synology username
      private: false

  vars:
    synoinfoconf:
      path: /etc/synoinfo.conf

  tasks:

    - name: Set disable reset button to true
      ansible.builtin.command: "/usr/syno/bin/synosetkeyvalue {{ synoinfoconf.path }} reset_button_disable yes"
