---

# This playbook is used for whenever setting up a new Pihole instance on a Raspberry Pi.
# The playbook is only intended to run initially in order to setup tasks that will most likely only be set once.
# It should also be used in case there is any drift to this setup that needs fixing.
# Other playbooks will maintain the installation of Pihole and further maintenence.

- name: Setup Raspberry Pi
  hosts: pimachines
  become: true
  roles:
    - install_packages
    - update_packages
