---

- name: Install dependencies
  hosts: nodes
  become: true
  tasks:

    - name: Install docker plugins core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: Docker
        description: Docker repository
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install docker engine and containerd
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
        state: present

    - name: Start docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Add docker group
      ansible.builtin.group:
        name: "{{ docker_group }}"
        state: present

    - name: Add ansible user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: "{{ docker_group }}"

    - name: Install Kubernetes
      ansible.builtin.dnf:
        name:
          - kubernetes-kubeadm
          - kubernetes-node
          - kubernetes-client
        state: present
