---

- name: Set SSH settings
  hosts: all
  become: true

  handlers:

    - name: restart ssh
      service:
        name: ssh
        state: restarted

  tasks:

    # Taken from https://github.com/geerlingguy/ansible-for-devops/blob/master/security/main.yml
    - name: Update SSH configuration to be more secure.
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: 'sshd -t -f %s'
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
      notify: restart ssh
