---
edgerouters:
  hosts:
    edgerouter1:
      ansible_host: 192.168.1.1
      ansible_user: ansible
      ansible_network_os: edgeos

nodes:
  hosts:
    kmain:
      ansible_host: 192.168.1.105
      ansible_user: kmain

    kworker:
      ansible_host: 192.168.1.104
      ansible_user: kworker1

    irishcoffee:
      ansible_host: 192.168.30.12
      ansible_user: jonas

  vars:
    etc_hosts:
      - ip: 192.168.1.105
        host: "kmain.local"

      - ip: 192.168.1.104
        host: "kworker1.local"

pimachines:
  hosts:
    pi01:
      ansible_host: 192.168.30.10

  vars:
    ansible_user: jserver
    hostname: margarita
    keys_repository: https://github.com/jlilja.keys
    dns_1: 1.1.1.1
    dns_2: 1.0.0.1
    privacy_level: 0

nas:
  hosts:
    ds418:
      ansible_host: 192.168.50.10
      ansible_user: "{{ synology_username }}"
