---
version: "3"

env:
  INVENTORY: hosts.yml

tasks:
  configure-synology:
    desc: "Set various configs for synology NAS"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK --ask-become-pass --ask-pass
    env:
      PLAYBOOK: configure-synology.yml

  create-ansible-user:
    desc: "Create ansible user with docker group"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: setup-ansible.yml
      INVENTORY: inventory/nodes.ini

  install-docker:
    desc: "Install docker on raspbian and ubuntu"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: install-docker.yml
      INVENTORY: inventory/nodes.ini

  update-packages:
    desc: "Update packages"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: update-packages.yml
      INVENTORY: inventory/nodes.ini

  setup-pubkey-auth:
    desc: "Create ansible user and set pubkey ssh authentication"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: setup-pubkey-auth.yml
      INVENTORY: inventory/nodes.ini


  setup-doco-cd:
    desc: "Setup doco-cd docker compose project"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: setup-doco-cd.yml
      INVENTORY: inventory/nodes.ini
