---
version: "3"

tasks:
  edgeroutersetup:
    desc: "Configure edgerouter"
    dir: "ansible"
    cmds:
      - ansible-playbook -i ./hosts.yml ./configure-edgerouter.yml --ask-pass

  bootstrap_pihole:
    desc: "Run playbook meant for an initial setup of a Pihole on a Raspberry Pi"
    dir: "ansible"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      INVENTORY: hosts.yml
      PLAYBOOK: bootstrap.yml

  update_packages:
    desc: Update apt packages on machine
    dir: "ansible"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      INVENTORY: hosts.yml
      PLAYBOOK: update-packages.yml

  update_pihole:
    desc: Update pihole
    dir: "ansible"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      INVENTORY: hosts.yml
      PLAYBOOK: update-pihole.yml
