---
version: "3"

env:
  INVENTORY: hosts.yml

tasks:
  configure-edgerouter:
    desc: "Configure edgerouter"
    cmds:
      - |
        docker run -it --rm --network="host" \
          -v "$PWD:/ansible" \
          -e "SSH_AUTH_SOCK=/.1password/agent.sock" \
          -v "$HOME/.1password/agent.sock:/.1password/agent.sock:ro" \
          -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro" \
          ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: configure-edgerouter.yml

  configure-edgerouter-firewall:
    desc: "Configure edgerouter firewall"
    cmds:
      - |
        docker run -it --rm --network="host" \
          -v "$PWD:/ansible" \
          -e "SSH_AUTH_SOCK=/.1password/agent.sock" \
          -v "$HOME/.1password/agent.sock:/.1password/agent.sock:ro" \
          -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro" \
          ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: configure-edgerouter-firewall.yml

  configure-edgerouter-groups:
    desc: "Configure edgerouter groups"
    cmds:
      - |
        docker run -it --rm --network="host" \
          -v "$PWD:/ansible" \
          -e "SSH_AUTH_SOCK=/.1password/agent.sock" \
          -v "$HOME/.1password/agent.sock:/.1password/agent.sock:ro" \
          -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro" \
          ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: configure-edgerouter-groups.yml

  configure-pihole:
    desc: "Run playbook meant for an initial setup of a Pihole on a Raspberry Pi"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK
    env:
      PLAYBOOK: configure-pihole.yml

  configure-synology:
    desc: "Set various configs for synology NAS"
    cmds:
      - |
        docker run -it --rm --network="host" \
          -v "$PWD:/ansible:ro" \
          -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro" \
          ansible-playbook -i $INVENTORY $PLAYBOOK --ask-become-pass --ask-pass
    env:
      PLAYBOOK: configure-synology.yml

  dnf-install-container-environment:
    desc: "Install docker and kubernetes"
    cmds:
      - ansible-playbook -i $INVENTORY $PLAYBOOK --ask-become-pass
    env:
      PLAYBOOK: dnf-install-packages.yml

  update-packages:
    desc: "Update packages"
    cmds:
      - |
        docker run -it --rm --network="host" \
          -e "SSH_AUTH_SOCK=/.1password/agent.sock" \
          -v "$HOME/.1password/agent.sock:/.1password/agent.sock:ro" \
          -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro" \
          -v "$PWD:/ansible:ro" \
          ansible-playbook -i $INVENTORY $PLAYBOOK --ask-become-pass
    env:
      PLAYBOOK: update-packages.yml

  harden-ssh:
    desc: "Secure ssh configs"
    cmds:
      - |
        docker run -it --rm --network="host" \
          -e "SSH_AUTH_SOCK=/.1password/agent.sock" \
          -v "$HOME/.1password/agent.sock:/.1password/agent.sock:ro" \
          -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro" \
          -v "$PWD:/ansible:ro" \
          ansible-playbook -i $INVENTORY $PLAYBOOK --ask-become-pass
    env:
      PLAYBOOK: harden-ssh.yml
