services:
  nginx:
    image: nginx:1.27.5@sha256:c15da6c91de8d2f436196f3a768483ad32c258ed4e1beb3d367a27ed67253e66
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  pihole:
    image: pihole/pihole:2025.03.0@sha256:6c872c3f8f1954423dbd1c7db661719b447e7b890e231489ada2a6a2904342ff
    environment:
      TZ: 'Europe/Stockholm'
    volumes:
      - './pihole.toml:/etc/pihole/pihole.toml'
