services:
  nginx:
    image: nginx:1.27.5@sha256:c15da6c91de8d2f436196f3a768483ad32c258ed4e1beb3d367a27ed67253e66
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  pihole:
    image: pihole/pihole:2025.05.1@sha256:db38df3e050606bd014c801c2cbb0b13f263d3122d3d817a8cbcee807688af24
    environment:
      TZ: 'Europe/Stockholm'
    ports:
      - 53:53
    restart: always
    volumes:
      - './pihole.toml:/etc/pihole/pihole.toml'
