services:
  nginx:
    image: nginx:1.27.5@sha256:fb39280b7b9eba5727c884a3c7810002e69e8f961cc373b89c92f14961d903a0
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  pihole:
    image: pihole/pihole:2025.05.1@sha256:db38df3e050606bd014c801c2cbb0b13f263d3122d3d817a8cbcee807688af24
    environment:
      TZ: 'Europe/Stockholm'
    volumes:
      - './pihole.toml:/etc/pihole/pihole.toml'
