services:
  # nginx:
  #   image: nginx:1.27.5@sha256:c15da6c91de8d2f436196f3a768483ad32c258ed4e1beb3d367a27ed67253e66
  #   ports:
  #     - 80:80
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  pihole:
    image: pihole/pihole:2025.06.1@sha256:7d8f83d8a904b25c6074c0798c106067e3a4f2e2caeea15791326f214566b47e
    environment:
      TZ: 'Europe/Stockholm'
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      - 80:80
    restart: unless-stopped
    volumes:
      - './pihole.toml:/etc/pihole/pihole.toml'
