services:
  # nginx:
  #   image: nginx:1.27.5@sha256:c15da6c91de8d2f436196f3a768483ad32c258ed4e1beb3d367a27ed67253e66
  #   ports:
  #     - 80:80
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  pihole:
    image: pihole/pihole:2025.07.1@sha256:f84c1654bfbafc44e2ac8447a1fa2fb739eae66395b4c179d2c59cb93e1321f3
    environment:
      TZ: 'Europe/Stockholm'
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      - 80:80
    restart: unless-stopped
    volumes:
      - './pihole.toml:/etc/pihole/pihole.toml'
