name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**/*.yml"
      - ".github/workflows/ansible-lint.yml"
      - "./requirements.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c # v26.4.0
