name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@492d840530aa2e2b3281165d2353134ad796b156
        with:
          args: "--profile=min --exclude=ansible/edgerouter/edgerouter.yml"
