name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**.yml"
      - ".github/workflows/ansible-lint.yml"
      - "./requirements.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run ansible-lint
        uses: ansible/ansible-lint@4114ad63edbc25dcd9afc4f41b29dbcbebdf21ca # v25.5.0
