name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**.yml"
      - ".github/workflows/ansible-link.yml"
      - "./requirements.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@3b5bee19c2102ea35bc8619795a72c5c73797fc7
