name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**.yml"
      - ".github/workflows/ansible-lint.yml"
      - "./requirements.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@50373efb440dd3b524956c075af715cd00eaf20b # v25.8.2
