name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@dfb8fea539b53a0f9615282615f1dca90e7ecb91
        with:
          args: "--profile=min --exclude=ansible/edgerouter/edgerouter.yml"
