name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**.yml"
      - ".github/workflows/ansible-link.yml"
      - "./requirements.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          requirements_file: "./requirements.yml"
