name: Ansible lint

on:
  pull_request:
    paths:
      - "./ansible/**/*.yml"
      - ".github/workflows/ansible-lint.yml"
      - "./requirements.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@262624cd0ab22a4221293216856c59671ce7aa5e # v26.6.0
