name: Format on push

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5

      - name: Run terraform apply
        run: terraform apply
