name: Docker build

on:
  workflow_dispatch:
  push:
    paths:
      - "dockerfiles/**"
      - ".github/workflows/docker-build.yml"

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Run Docker bake
        uses: docker/bake-action@3acf805d94d93a86cce4ca44798a76464a75b88c # v6.9.0
        with:
          source: .
          workdir: dockerfiles/ansible
          files: docker-bake.hcl
          push: false
