name: Docker build

on:
  workflow_dispatch:
  push:
    paths:
      - "dockerfiles/**"
      - ".github/workflows/docker-build.yml"

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Run Docker bake
        uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
        with:
          source: .
          workdir: dockerfiles/ansible
          files: docker-bake.hcl
          push: false
