name: Docker build

on:
  workflow_dispatch:
  push:
    paths:
      - "dockerfiles/**"
      - ".github/workflows/docker-build.yml"

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@138de3b6464b863fed6a98c1fae46faa58f98dee # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@aa1e2a0b496d6cd3474071c7b0ab0eea5948de3a # v3

      - name: Run Docker bake
        uses: docker/bake-action@c48383c7fd6d2a1a3459884f6224098f671c545d # v6
        with:
          source: .
          workdir: dockerfiles/ansible
          files: docker-bake.hcl
          push: false
