name: Docker build

on:
  workflow_dispatch:
  push:
    paths:
      - "dockerfiles/**"
      - ".github/workflows/docker-build.yml"

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@138de3b6464b863fed6a98c1fae46faa58f98dee # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@afeb29a6e0d7d6258844ecabe6eba67d13443680 # v3

      - name: Run Docker bake
        uses: docker/bake-action@8f9e95c9aa0181f735899e61e36d9477cb08ffc5 # v6
        with:
          source: .
          workdir: dockerfiles/ansible
          files: docker-bake.hcl
          push: false
