name: Docker build

on:
  workflow_dispatch:
  push:
    paths:
      - "dockerfiles/**"
      - ".github/workflows/docker-build.yml"

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker bake
        uses: docker/bake-action@v6
        with:
          source: ./dockerfiles/ansible
          files: ./dockerfiles/ansible/docker-bake.hcl
          push: false
