---
name: Apply Terraform code on main

on:
  push:
    paths:
      - "apps/cloudflare/*.tf"
      - "apps/cloudflare/*.hcl"
      - "apps/modules/**/*.tf"

      - ".github/workflows/terraform-apply.yml"
      - ".github/workflows/terraform-plan.yml"
    branches:
      - main
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Taskfile
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::524080394605:role/TFGithubOIDC
          aws-region: eu-north-1

      - name: Terraform Init
        id: init
        run: task terraform:cloudflare:init

      - name: Terraform Apply
        id: apply
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
        run: task terraform:cloudflare:apply
