---
name: Format Terraform code on push

on:
  push:
    paths:
      - "**/*.tf"

env:
  TF_IN_AUTOMATION: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Taskfile
        uses: arduino/setup-task@7da076a31d22e32a0b08d90f20a630097a7100dd # v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@e708d31c3d84ac0e520fa59e11a6c465913ebfc4 # v3

      - name: Run terraform fmt check
        run: task terraform:cloudflare:format-check
