---
name: Format Terraform code on push

on:
  push:
    paths:
      - "**/*.tf"

env:
  TF_IN_AUTOMATION: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Taskfile
        uses: arduino/setup-task@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.5

      - name: Run terraform fmt check
        run: task terraform:cloudflare:format
