---
name: Format Terraform code on push

on:
  push:
    paths:
      - "**/*.tf"

env:
  TF_IN_AUTOMATION: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Setup Taskfile
        uses: arduino/setup-task@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.5

      - name: Run terraform fmt check
        run: task terraform:cloudflare:format
