---
name: Apply Terraform code on main

on:
  push:
    paths:
      - "terraform/cloudflare/*.tf"
      - "terraform/cloudflare/*.hcl"
      - "terraform/modules/**/*.tf"

      - ".github/workflows/terraform-apply.yml"
      - ".github/workflows/terraform-plan.yml"
    branches:
      - main
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Taskfile
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::524080394605:role/TFGithubOIDC
          aws-region: eu-north-1

      - name: Terraform Init
        id: init
        run: task terraform:cloudflare:init

      - name: Terraform Apply
        id: apply
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
        run: task terraform:cloudflare:apply
