---
name: Format Terraform code on push

on:
  push:
    paths:
      - "**/*.tf"

env:
  TF_IN_AUTOMATION: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Taskfile
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Run terraform fmt check
        run: task terraform:cloudflare:format-check
