---
name: Apply Terraform code on main

on:
  push:
    paths:
      - "**/*.tf"
      - "**/*.hcl"
    branches:
      - main
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Taskfile
        uses: arduino/setup-task@7da076a31d22e32a0b08d90f20a630097a7100dd # v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@817023b5c82d2c7e8a83ec15dd1a7352c0cd875f # v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4
        with:
          role-to-assume: arn:aws:iam::524080394605:role/TFGithubOIDC
          aws-region: eu-north-1

      - name: Terraform Init
        id: init
        run: task terraform:cloudflare:init

      - name: Terraform Apply
        id: apply
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
          TF_VAR_protonmail_verification: ${{ secrets.TF_VAR_PROTONMAIL_VERIFICATION }}
        run: task terraform:cloudflare:apply
