---
name: Plan Terraform code on PR

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.hcl"
      - ".github/workflows/terraform-apply.yml"
      - ".github/workflows/terraform-plan.yml"
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Taskfile
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@817023b5c82d2c7e8a83ec15dd1a7352c0cd875f # v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: arn:aws:iam::524080394605:role/TFGithubOIDC
          aws-region: eu-north-1

      - name: Terraform Init
        run: task terraform:cloudflare:init

      - name: Terraform Validate
        run: task terraform:cloudflare:validate

      - name: Terraform Format
        run: task terraform:cloudflare:format-check

      - name: Terraform Plan
        id: plan
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
          TF_VAR_protonmail_verification: ${{ secrets.TF_VAR_PROTONMAIL_VERIFICATION }}
        run: task terraform:cloudflare:plan

      - name: Update PR
        uses: actions/github-script@v7
        id: plan-comment
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            Show Plan

            \`\`\`${process.env.PLAN}\`\`\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
