---
name: Format Terraform code on push

on:
  push:
    paths:
      - "**/*.tf"

env:
  TF_IN_AUTOMATION: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Taskfile
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Run terraform fmt check
        run: task terraform:cloudflare:format-check
