---
version: "3"

tasks:
  create-iso-from-files:
    cmds:
      - rm -r iso || true
      - rm ks.iso || true
      - mkdir iso
      - cp ks.cfg cloud-init.yml iso
      - xorriso -as mkisofs -o ks.iso iso/

  write-iso-to-usb:
    cmds:
      - sudo dd if=ks.iso of=/dev/sda bs=8M status=progress
